### PR TITLE
Milestone 1 fixes

### PR DESCRIPTION
**Pull request by SimplyTim**
I made some minor changes, prior to starting work for milestone 2.

Please review. Thanks.

### CODE REVIEW

**Comment by SimplyTim** [comment]
Okay, so additionally, I added versions and cleaned up the `environment.yml` file, as well as removing unusued imports from the analysis.

This change to the environment.yml will be useful for generating the conda.lock file in next milestone.

**Review by BryanLee06 — APPROVED** [review]
Looks good! thanks for updating the versions

**Review by BryanLee06 — APPROVED** [review]
Looks good!

**Review by BryanLee06 — COMMENTED** [review]
Looks good!

**Review by wzhu8410 — APPROVED** [review]
Looks good thanks!

**Review by BryanLee06 — APPROVED** [review]
Looks good! Approved

**Pull request merged**
